"""
config/config_subtitle.yml 전사본 (mediaflow 파이프라인 설정).

⚠️  이 파일은 backend/tools/sync_from_mediaflow.py 가 생성합니다. 직접 수정하지 마세요.
    동기화 날짜: 2026-09-16

- VALIDATION_PARAMS : 방송사별 글자 수 / 줄 수 / 바이트 / 가중치
- STAGE1 / STAGE2   : 실행 순서 그대로의 후처리 · 검증 목록
                      (STAGE2 방송사 항목의 *_extend 는 공통 뒤에 이어 붙고,
                       *_remove 에 적힌 함수는 공통에서 빠진다)
- FINAL             : 납품 확장자 · 마침표 제거 · 배너
"""

VALIDATION_PARAMS = {'common': {'max_length': 18,
            'max_lines': 2,
            'max_byte_length': 36,
            'weight_kor': 1.0,
            'weight_etc': 1.0},
 'LGHV': {},
 'SKBB': {'max_length': 20, 'max_lines': 1, 'max_byte_length': 40},
 'JTBC': {},
 'TVCS': {},
 'TVNG': {'max_length': 20, 'max_lines': 2, 'weight_etc': 0.5},
 'DLIV': {'max_length': 17, 'max_lines': 3, 'max_byte_length': 34},
 'KBS': {'max_length': 20, 'max_lines': 1, 'max_byte_length': 40}}

STAGE1 = {'common': {'postprocess': [{'name': 'postprocess_remove_delete_tag', 'type': 'multi_subtitle'},
                            {'name': 'postprocess_strip_whitespace', 'type': 'content_only'},
                            {'name': 'postprocess_trim_speaker_spaces', 'type': 'content_only'},
                            {'name': 'postprocess_add_speaker_space', 'type': 'content_only'},
                            {'name': 'postprocess_normalize_spaces', 'type': 'content_only'},
                            {'name': 'postprocess_add_space_after_special_punctuation',
                             'type': 'content_only'},
                            {'name': 'postprocess_remove_wrong_punctuation',
                             'type': 'content_only'},
                            {'name': 'postprocess_normalize_ellipsis', 'type': 'content_only'},
                            {'name': 'postprocess_normalize_repeats', 'type': 'content_only'},
                            {'name': 'postprocess_normalize_wrong_mixed_punctuations',
                             'type': 'content_only'},
                            {'name': 'postprocess_fix_position_tag', 'type': 'content_only'},
                            {'name': 'postprocess_fix_yae_yee', 'type': 'content_only'},
                            {'name': 'postprocess_normalize_mix_characters',
                             'type': 'content_only'},
                            {'name': 'postprocess_normalize_comma_space', 'type': 'content_only'},
                            {'name': 'postprocess_normalize_period_space', 'type': 'content_only'},
                            {'name': 'postprocess_sync_overlap', 'type': 'timing'},
                            {'name': 'postprocess_reset_subtitles_from_list',
                             'type': 'multi_subtitle'}],
            'validate': [{'name': 'validate_pair_characters', 'type': 'content_only'},
                         {'name': 'validate_special_characters_allow_music_note',
                          'type': 'content_only'},
                         {'name': 'validate_empty_content', 'type': 'content_only'},
                         {'name': 'validate_ellipsis_count',
                          'type': 'content_with_params',
                          'params': {'criterion': 5}},
                         {'name': 'validate_sync_negative_or_zero', 'type': 'timing'}]}}

STAGE2 = {'common': {'validate': [{'name': 'validate_length_lines',
                          'type': 'content_with_validation_params',
                          'params': {'valid_type': 'length'}},
                         {'name': 'validate_line_count', 'type': 'content_with_validation_params'},
                         {'name': 'validate_pair_characters', 'type': 'content_only'},
                         {'name': 'validate_sync_negative_or_zero', 'type': 'timing'},
                         {'name': 'validate_ellipsis_count',
                          'type': 'content_with_params',
                          'params': {'criterion': 5}}],
            'postprocess': [{'name': 'postprocess_remove_delete_tag', 'type': 'multi_subtitle'},
                            {'name': 'postprocess_strip_whitespace', 'type': 'content_only'},
                            {'name': 'postprocess_trim_speaker_spaces', 'type': 'content_only'},
                            {'name': 'postprocess_add_speaker_space', 'type': 'content_only'},
                            {'name': 'postprocess_normalize_spaces', 'type': 'content_only'},
                            {'name': 'postprocess_add_space_after_special_punctuation',
                             'type': 'content_only'},
                            {'name': 'postprocess_remove_wrong_punctuation',
                             'type': 'content_only'},
                            {'name': 'postprocess_normalize_ellipsis', 'type': 'content_only'},
                            {'name': 'postprocess_normalize_repeats', 'type': 'content_only'},
                            {'name': 'postprocess_normalize_wrong_mixed_punctuations',
                             'type': 'content_only'},
                            {'name': 'postprocess_fix_position_tag', 'type': 'content_only'},
                            {'name': 'postprocess_fix_yae_yee', 'type': 'content_only'},
                            {'name': 'postprocess_normalize_mix_characters',
                             'type': 'content_only'},
                            {'name': 'postprocess_normalize_comma_space', 'type': 'content_only'},
                            {'name': 'postprocess_normalize_period_space', 'type': 'content_only'},
                            {'name': 'postprocess_reset_subtitles_from_list',
                             'type': 'multi_subtitle'}]},
 'LGHV': {'validate_extend': [{'name': 'validate_special_characters_allow_music_note',
                               'type': 'content_only'},
                              {'name': 'validate_overlapped_over_lines', 'type': 'pair_validation'},
                              {'name': 'validate_overlapped_only_text_for_lghv',
                               'type': 'pair_validation'}],
          'postprocess_extend': [{'name': 'postprocess_over_length_lines',
                                  'type': 'content_with_params',
                                  'params': {'max_length': 18}},
                                 {'name': 'postprocess_remove_star_and_angle_for_lghv',
                                  'type': 'content_only'},
                                 {'name': 'postprocess_remove_not_pair_paren_quotes_for_lghv',
                                  'type': 'content_only'},
                                 {'name': 'postprocess_normalize_music_to_double_note_for_lghv',
                                  'type': 'content_only'},
                                 {'name': 'postprocess_keep_bracket_music_note_and_remove_others_for_lghv',
                                  'type': 'content_only'},
                                 {'name': 'postprocess_mark_overlapped_multi_speaker',
                                  'type': 'multi_subtitle',
                                  'params': {'reassign_index': True}},
                                 {'name': 'postprocess_add_period_between_lines',
                                  'type': 'content_with_params',
                                  'params': {'max_chars_per_line': 18, 'max_lines': 2}},
                                 {'name': 'postprocess_add_period_between_subs',
                                  'type': 'multi_subtitle',
                                  'params': {'max_chars_per_line': 18, 'max_lines': 2}},
                                 {'name': 'postprocess_add_period_between_subs',
                                  'type': 'multi_subtitle'},
                                 {'name': 'postprocess_reset_subtitles_from_list',
                                  'type': 'multi_subtitle'}],
          'validate_remove': [],
          'postprocess_remove': []},
 'SKBB': {'validate_extend': [{'name': 'validate_special_characters', 'type': 'content_only'},
                              {'name': 'validate_hyphen_no_space_after_for_skbb',
                               'type': 'content_only'},
                              {'name': 'validate_mosaic_count_for_skbb',
                               'type': 'content_with_params',
                               'params': {'criterion': 2}},
                              {'name': 'validate_overlapped_over_lines', 'type': 'pair_validation'},
                              {'name': 'validate_sync_overlapped', 'type': 'pair_validation'}],
          'postprocess_extend': [{'name': 'postprocess_remove_first_hypn',
                                  'type': 'content_with_params',
                                  'params': {'punctuation': '-'}},
                                 {'name': 'postprocess_remove_space_after_hypn',
                                  'type': 'content_only'},
                                 {'name': 'postprocess_remove_star_and_angle_for_skbb',
                                  'type': 'content_only'},
                                 {'name': 'postprocess_remove_not_pair_paren_quotes_for_skbb',
                                  'type': 'content_only'},
                                 {'name': 'postprocess_normalize_asterisk_for_skbb',
                                  'type': 'content_only'},
                                 {'name': 'postprocess_add_period_between_lines',
                                  'type': 'content_with_params',
                                  'params': {'max_chars_per_line': 20, 'max_lines': 1}},
                                 {'name': 'postprocess_add_period_between_subs',
                                  'type': 'multi_subtitle',
                                  'params': {'max_chars_per_line': 20, 'max_lines': 1}},
                                 {'name': 'postprocess_reset_subtitles_from_list',
                                  'type': 'multi_subtitle'}],
          'validate_remove': [],
          'postprocess_remove': []},
 'JTBC': {'validate_extend': [{'name': 'validate_special_characters_allow_music_note',
                               'type': 'content_only'},
                              {'name': 'validate_overlapped_over_lines',
                               'type': 'pair_validation'}],
          'postprocess_extend': [{'name': 'postprocess_over_length_lines',
                                  'type': 'content_with_params',
                                  'params': {'max_length': 18}},
                                 {'name': 'postprocess_remove_other_characters',
                                  'type': 'content_only'},
                                 {'name': 'postprocess_remove_not_pair_characters',
                                  'type': 'content_only'},
                                 {'name': 'postprocess_mark_overlapped_multi_speaker',
                                  'type': 'multi_subtitle',
                                  'params': {'reassign_index': True}},
                                 {'name': 'postprocess_add_period_between_lines',
                                  'type': 'content_with_params',
                                  'params': {'max_chars_per_line': 18, 'max_lines': 2}},
                                 {'name': 'postprocess_add_period_between_subs',
                                  'type': 'multi_subtitle',
                                  'params': {'max_chars_per_line': 18, 'max_lines': 2}},
                                 {'name': 'postprocess_reset_subtitles_from_list',
                                  'type': 'multi_subtitle'}],
          'validate_remove': [],
          'postprocess_remove': []},
 'TVCS': {'validate_extend': [{'name': 'validate_sync_overlapped', 'type': 'pair_validation'}],
          'postprocess_extend': [{'name': 'postprocess_remove_all_star', 'type': 'content_only'},
                                 {'name': 'postprocess_over_length_lines_middle',
                                  'type': 'content_with_params',
                                  'params': {'max_length': 18}}],
          'validate_remove': [],
          'postprocess_remove': []},
 'TVNG': {'validate_extend': [{'name': 'validate_comma_space', 'type': 'content_only'},
                              {'name': 'validate_overlapped_over_lines',
                               'type': 'pair_validation'},
                              {'name': 'validate_tilde_remains',
                               'params': {'allow_number_range': True},
                               'type': 'content_with_params'}],
          'postprocess_extend': [{'name': 'postprocess_normalize_music_to_single_note_for_tvng',
                                  'type': 'content_only'},
                                 {'name': 'postprocess_mark_overlapped_multi_speaker',
                                  'type': 'multi_subtitle',
                                  'params': {'reassign_index': True}},
                                 {'name': 'postprocess_apply_overlap_hyphen_for_all_speech',
                                  'type': 'multi_subtitle',
                                  'params': {'dash_prefix': '- '}},
                                 {'name': 'postprocess_reset_subtitles_from_list',
                                  'type': 'multi_subtitle'}],
          'validate_remove': [],
          'postprocess_remove': []},
 'DLIV': {'validate_extend': [{'name': 'validate_hyphen_no_space_after_for_skbb',
                               'type': 'content_only'},
                              {'name': 'validate_sync_short_duration',
                               'type': 'timing',
                               'params': {'min_duration_sec': 1.0}},
                              {'name': 'validate_overlapped_accumulated_lines',
                               'type': 'multi_validation',
                               'params': {'max_lines': 3}},
                              {'name': 'validate_sync_gap',
                               'type': 'multi_validation',
                               'params': {'gap_sec': 0.083}}],
          'postprocess_extend': [{'name': 'postprocess_remove_space_after_hypn',
                                  'type': 'content_only'},
                                 {'name': 'postprocess_adjust_subtitle_gaps',
                                  'type': 'multi_subtitle',
                                  'params': {'gap_sec': 0.083}},
                                 {'name': 'postprocess_adjust_short_sync',
                                  'type': 'multi_subtitle',
                                  'params': {'min_duration_sec': 1.0, 'gap_sec': 0.083}},
                                 {'name': 'postprocess_add_period_between_lines',
                                  'type': 'content_with_params',
                                  'params': {'max_chars_per_line': 17, 'max_lines': 3}},
                                 {'name': 'postprocess_add_period_between_subs',
                                  'type': 'multi_subtitle',
                                  'params': {'max_chars_per_line': 17, 'max_lines': 3}},
                                 {'name': 'postprocess_reset_subtitles_from_list',
                                  'type': 'multi_subtitle'}],
          'validate_remove': [],
          'postprocess_remove': []},
 'KBS': {'validate_extend': [{'name': 'validate_line_count_allow_hyphen',
                              'type': 'content_with_params',
                              'params': {'max_lines': 1, 'max_lines_with_hyphen': 2}}],
         'postprocess_extend': [{'name': 'postprocess_mark_overlapped_multi_speaker',
                                 'type': 'multi_subtitle',
                                 'params': {'max_lines_per_sub': 1,
                                            'max_merged_lines': 2,
                                            'multi_speaker_prefix': '-',
                                            'multi_overlap_strategy': 'best_pair',
                                            'reassign_index': True}}],
         'validate_remove': ['validate_line_count'],
         'postprocess_remove': []}}

FINAL = {'common': {'banner': False,
            'delivery_extension': '.srt',
            'remove_punctuation': False,
            'punctuation_list': ['.']},
 'LGHV': {'banner': False,
          'delivery_extension': '.srt',
          'remove_punctuation': True,
          'punctuation_list': ['.']},
 'SKBB': {'banner': False, 'delivery_extension': '.smi', 'remove_punctuation': False},
 'JTBC': {'banner': True,
          'banner_setting': {'banner_sentence': '장애인방송 VOD 제작지원 : 방송미디어통신위원회‧시청자미디어재단',
                             'banner_start': '00:00:00',
                             'banner_end': '00:00:05'},
          'delivery_extension': '.srt',
          'remove_punctuation': True,
          'punctuation_list': ['.']},
 'TVCS': {'banner': True,
          'banner_setting': {'banner_sentence': '장애인방송 VOD 제작지원 : 방송미디어통신위원회‧시청자미디어재단',
                             'banner_start': '00:00:00',
                             'banner_end': '00:00:07'},
          'delivery_extension': '.vtt',
          'remove_punctuation': False},
 'TVNG': {'banner': False,
          'delivery_extension': '.vtt',
          'remove_punctuation': True,
          'punctuation_list': ['.']},
 'DLIV': {'banner': False, 'delivery_extension': '.srt', 'remove_punctuation': False},
 'KBS': {'banner': True,
         'banner_setting': {'banner_sentence': '장애인방송 VOD 제작지원 : 방송미디어통신위원회‧시청자미디어재단',
                            'banner_start': '00:00:00',
                            'banner_end': '00:00:05',
                            'gap_before_sec': 0.1},
         'delivery_extension': '.srt',
         'remove_punctuation': True,
         'punctuation_list': ['.']}}

# 방송사 코드 (config 에 등장하는 순서)
BROADCASTER_CODES = ['LGHV', 'SKBB', 'JTBC', 'TVCS', 'TVNG', 'DLIV', 'KBS']
