"""
함수명 → 소스코드 매핑 (자동 생성)
"""

SOURCE_CODES = {
    "postprocess_add_period_between_lines": 'def postprocess_add_period_between_lines(sentence, ending_punctuation=".!?~", **kwargs):\n    """줄 간 마침표 삽입"""\n    if sentence is None: return ""\n    lines = sentence.splitlines()\n    if len(lines) < 2: return sentence\n    for i in range(len(lines) - 1):\n        cur = lines[i].rstrip()\n        nxt = lines[i + 1].strip()\n        if not cur or not nxt: continue\n        if not (nxt.startswith("-") or nxt.startswith("(")): continue\n        if cur.endswith("...") or cur[-1] in ending_punctuation or cur[-1] in ")]": continue\n        lines[i] = cur + "."\n    return "\\n".join(lines)',

    "postprocess_add_period_between_subs": 'def postprocess_add_period_between_subs(subs, ending_punctuation=".!?~", **kwargs):\n    """자막 간 마침표 삽입"""\n    if not subs: return subs\n    for i in range(len(subs) - 1):\n        cur, nxt = subs[i], subs[i + 1]\n        if not cur.content or not nxt.content: continue\n        nxt_first = nxt.content.splitlines()[0].strip()\n        if not (nxt_first.startswith("-") or nxt_first.startswith("(")): continue\n        cur_lines = cur.content.splitlines()\n        last = cur_lines[-1].rstrip()\n        if not last or last.endswith("...") or last[-1] in ending_punctuation or last[-1] in ")]": continue\n        cur_lines[-1] = last + "."\n        cur.content = "\\n".join(cur_lines)\n    return subs',

    "postprocess_add_space_after_special_punctuation": 'def postprocess_add_space_after_special_punctuation(sentence: str, **kwargs) -> str:\n    """... ? ! 뒤에 바로 글자가 오면 공백 1칸 추가 (맨 앞은 제외)"""\n    if sentence is None:\n        return ""\n    def _repl(m):\n        if m.start(1) == 0:\n            return m.group(1) + m.group(2)\n        return f"{m.group(1)} {m.group(2)}"\n    pattern1 = re.compile(r\'(\\.{3,}|[?!])([가-힣A-Za-z0-9])\')\n    pattern2 = re.compile(r\'(?<!\\d)(~)([가-힣A-Za-z0-9])\')\n    lines = sentence.splitlines()\n    out_lines = []\n    for line in lines:\n        new_line = pattern1.sub(_repl, line)\n        new_line = pattern2.sub(_repl, new_line)\n        out_lines.append(new_line)\n    return "\\n".join(out_lines)',

    "postprocess_add_speaker_space": 'def postprocess_add_speaker_space(sentence: str, **kwargs) -> str:\n    """화자 표시 닫는 괄호 뒤 공백 추가"""\n    return re.sub(r"\\)([^\\s\\[\\(])", r") \\1", sentence)',

    "postprocess_adjust_or_merge_short_sync": 'def postprocess_adjust_or_merge_short_sync(subs, min_duration_sec=1.0, max_lines_after_merge=3, gap_sec=0.083, **kwargs):\n    """DLIV: 1초 미만 자막 처리 (연장 또는 병합)"""\n    # 실제 코드는 postprocess_stage2.py 참조 (약 100줄)\n    pass',

    "postprocess_adjust_subtitle_gaps": 'def postprocess_adjust_subtitle_gaps(subs, gap_sec=0.083, **kwargs):\n    """DLIV: 자막 간격 조정 (gap_sec 미만이면 앞 자막 end 조정)"""\n    # 실제 코드는 postprocess_stage2.py 참조\n    pass',

    "postprocess_convert_characters": 'def postprocess_convert_characters(text, from_chars="[]", to_chars="()", **kwargs):\n    """기호 변경 (예: [] -> ())"""\n    if text is None: return ""\n    if len(from_chars) == len(to_chars):\n        return text.translate(str.maketrans(from_chars, to_chars))\n    return text',

    "postprocess_keep_bracket_music_note_and_remove_others_for_lghv": 'def postprocess_keep_bracket_music_note_and_remove_others_for_lghv(text, **kwargs):\n    """LGHV: [♫ ...]만 살리고 나머지 음표 제거"""\n    if text is None: return ""\n    SENTINEL = "\\uE000"\n    out = re.sub(r"\\[\\u266B\\s*", "[\\u266B ", text)\n    out = out.replace("[\\u266B ", f"[{SENTINEL} ")\n    out = re.sub(r"[\\u266B]", "", out)\n    out = out.replace(f"[{SENTINEL} ", "[\\u266B ")\n    return out',

    "postprocess_mark_overlapped_multi_speaker": 'def postprocess_mark_overlapped_multi_speaker(subs, reassign_index=True, multi_speaker_prefix="- ", max_lines_per_sub=1, multi_overlap_strategy="best_pair", max_merged_lines=2, **kwargs):\n    """오버랩 다화자 구간 처리 (2개: 하이픈 추가 후 병합, 3개+: 전략별 처리)"""\n    # 실제 코드는 postprocess_stage2.py 참조 (약 200줄)\n    pass',

    "postprocess_merge_overlapped_sync": 'def postprocess_merge_overlapped_sync(subs, max_lines_per_sub=1, **kwargs):\n    """오버랩 자막 병합 (겹침만 처리, 맞닿음은 제외)"""\n    if not subs:\n        return subs\n    def _within(text):\n        if text is None: return False\n        return text.strip().count("\\n") < max_lines_per_sub\n    subs = sorted(subs, key=lambda x: (x.start, x.end))\n    result, i, n = [], 0, len(subs)\n    while i < n:\n        cur = subs[i]\n        if i == n - 1:\n            result.append(cur); break\n        nxt = subs[i + 1]\n        if cur.end > nxt.start and _within(cur.content) and _within(nxt.content):\n            import srt\n            merged = srt.Subtitle(index=cur.index, start=cur.start,\n                end=max(cur.end, nxt.end), content=f"{cur.content}\\n{nxt.content}")\n            result.append(merged); i += 2\n        else:\n            result.append(cur); i += 1\n    return result',

    "postprocess_normalize_asterisk_for_skbb": 'def postprocess_normalize_asterisk_for_skbb(sentence, **kwargs):\n    """SKBB: 별표 정규화 (2개 이상→**, 1개→그대로)"""\n    def repl(m):\n        return "**" if len(m.group(0)) >= 2 else "asterisks"\n    result = re.sub(r"\\*{2,}", repl, sentence)\n    return re.sub(r"\\s+$", "", result)',

    "postprocess_normalize_ellipsis": 'def postprocess_normalize_ellipsis(sentence: str, **kwargs) -> str:\n    """말줄임표 정규화: 4개 이상 → 3개"""\n    def _replace_dots(match):\n        dots = match.group(0)\n        count = len(dots)\n        if count >= 4:\n            return "..."\n        if count == 3:\n            return "..."\n        return dots\n    result = re.sub(r"\\.{2,}", _replace_dots, sentence)\n    result = re.sub(r"\\s+$", "", result)\n    return result',

    "postprocess_normalize_mix_characters": 'def postprocess_normalize_mix_characters(sentence, pattern=r"[!?.,~]+", **kwargs) -> str:\n    """혼합 특수기호 런을 마지막 단위만 남김"""\n    if sentence is None:\n        return ""\n    tail_unit = re.compile(r"(?:\\.\\.\\.|\\.|[!?~,])$")\n    def _collapse_run(m):\n        run = m.group(0)\n        if run == "..":\n            return run\n        last = tail_unit.search(run).group(0)\n        return "..." if last == "..." else last\n    return re.sub(pattern, _collapse_run, sentence)',

    "postprocess_normalize_music_to_double_note_for_lghv": 'def postprocess_normalize_music_to_double_note_for_lghv(text, **kwargs):\n    """LGHV: 음표 통일 (♫로)"""\n    if text is None: return ""\n    return re.sub(r"[\\u266A\\u266B\\u266C\\u266D\\u266E\\u266F]", "\\u266B", text)',

    "postprocess_normalize_music_to_single_note_for_tvng": 'def postprocess_normalize_music_to_single_note_for_tvng(text, **kwargs):\n    """TVING: 음표 통일 (♪로)"""\n    if text is None: return ""\n    return re.sub(r"[\\u266A\\u266B\\u266C\\u266D\\u266E\\u266F]", "\\u266A", text)',

    "postprocess_normalize_repeats": 'def postprocess_normalize_repeats(sentence, **kwargs) -> str:\n    """같은 특수기호 반복을 1개로 축약 (! ? , ~)"""\n    if sentence is None:\n        return ""\n    return re.sub(r"([!?,~])\\1+", r"\\1", sentence)',

    "postprocess_normalize_spaces": 'def postprocess_normalize_spaces(sentence: str, **kwargs) -> str:\n    """연속된 공백을 단일 공백으로 정규화"""\n    return re.sub(r"[^\\S\\r\\n]{2,}", " ", sentence)',

    "postprocess_normalize_wrong_mixed_punctuations": 'def postprocess_normalize_wrong_mixed_punctuations(sentence, **kwargs) -> str:\n    """잘못된 특수문자/구두점/오탈자 표기를 정규화"""\n    if sentence is None:\n        return ""\n    return (\n        sentence.replace("\\u2018", "\'")\n        .replace("\\u2019", "\'")\n        .replace("\\uff0e", ".")\n        .replace("\\u201c", "")\n        .replace("\\u201d", "")\n        .replace("\\uff02", "")\n        .replace("\\u00b7", ".")\n        .replace("\\uacd8", "\\uacb0")\n        .replace("\\uaf10", "\\uaed8")\n    )',

    "postprocess_over_length_lines": 'def postprocess_over_length_lines(text, max_length=18, **kwargs):\n    """18글자 기준 줄바꿈"""\n    if text is None: return ""\n    lines = text.splitlines()\n    out = []\n    for line in lines:\n        if not line or len(line) <= max_length:\n            out.append(line); continue\n        words = line.split()\n        current = ""\n        for word in words:\n            candidate = word if not current else current + " " + word\n            if len(candidate) > max_length and current:\n                out.append(current); current = word\n            else:\n                current = candidate\n        if current:\n            out.append(current)\n    return "\\n".join(out)',

    "postprocess_remove_first_hypn": 'def postprocess_remove_first_hypn(sentence, punctuation=None, **kwargs):\n    """SKBB: 첫 자막의 시작 하이픈 제거"""\n    if not sentence: return sentence\n    subtitle_index = kwargs.get(\'subtitle_index\', None)\n    if subtitle_index is None or subtitle_index != 1: return sentence\n    if punctuation is None: punctuation = "-"\n    i = 0\n    while i < len(sentence) and sentence[i].isspace(): i += 1\n    if i < len(sentence) and sentence[i] in punctuation:\n        return sentence[:i] + sentence[i+1:]\n    return sentence',

    "postprocess_remove_last_punctuation": 'def postprocess_remove_last_punctuation(sentence, punctuation=None, **kwargs):\n    """마지막 구두점 제거 (말줄임표 \'...\' 보존)"""\n    if sentence is None: return ""\n    if punctuation is None: punctuation = ["."]\n    lines = sentence.splitlines()\n    out = []\n    for line in lines:\n        s = line.rstrip()\n        if not s or s.endswith("..."):\n            out.append(line); continue\n        if s[-1] in punctuation:\n            s = s[:-1]\n        out.append(s)\n    return "\\n".join(out)',

    "postprocess_remove_mid_period": 'def postprocess_remove_mid_period(sentence, **kwargs):\n    """문장 중간 마침표 제거 (소수/말줄임표/\'..\' 제외)"""\n    if sentence is None: return ""\n    lines = sentence.splitlines()\n    out = []\n    for line in lines:\n        lt = line; kept = []\n        def _keep(m):\n            kept.append(m.group(0))\n            return f"\\uE000{len(kept)-1}\\uE001"\n        lt = re.sub(r"\\.{3,}", _keep, lt)\n        lt = re.sub(r"\\.\\.", _keep, lt)\n        lt = re.sub(r"(?<!\\d)\\.(?!\\d)(?!\\s*$)", "", lt)\n        lt = re.sub(r"\\uE000(\\d+)\\uE001", lambda m: kept[int(m.group(1))], lt)\n        out.append(lt)\n    return "\\n".join(out)',

    "postprocess_remove_not_pair_characters": 'def postprocess_remove_not_pair_characters(content, pair_char=None, **kwargs):\n    """한쌍이 아니면 삭제 (괄호/따옴표/기호)"""\n    if content is None: return ""\n    if pair_char is None:\n        pair_char = {"(": ")", "[": "]", \'"\': \'"\', "\'": "\'", "<": ">", "\\u266A": "\\u266A"}\n    flat = content.replace("\\n", " ")\n    text = content\n    for open_char, close_char in pair_char.items():\n        open_count = flat.count(open_char)\n        close_count = flat.count(close_char)\n        if open_char == close_char:\n            if open_count % 2 != 0:\n                text = text.replace(open_char, "")\n            continue\n        if open_count != close_count:\n            text = text.replace(open_char, "").replace(close_char, "")\n    return text',

    "postprocess_remove_not_pair_paren_quotes_for_lghv": 'def postprocess_remove_not_pair_paren_quotes_for_lghv(text, **kwargs):\n    """LGHV: 짝 안 맞는 괄호/따옴표 제거"""\n    if text is None: return ""\n    return postprocess_remove_not_pair_characters(text, pair_char={"(": ")", \'"\': \'"\', "\'": "\'"})',

    "postprocess_remove_not_pair_paren_quotes_for_skbb": 'def postprocess_remove_not_pair_paren_quotes_for_skbb(text, **kwargs):\n    """SKBB: 짝 안 맞는 작은따옴표, 꺾쇠만 제거"""\n    if text is None: return ""\n    return postprocess_remove_not_pair_characters(text, pair_char={"\'": "\'", "<": ">"})',

    "postprocess_remove_other_characters": 'def postprocess_remove_other_characters(text, **kwargs):\n    """JTBC: 통합 기호 제거 (*, ♪, ♫, [], (), <>, ^)"""\n    if text is None: return ""\n    out = re.sub(r"[\\*\\u266A\\u266B\\[\\]\\(\\)<>\\^]", "", text)\n    return out',

    "postprocess_remove_space_after_hypn": 'def postprocess_remove_space_after_hypn(sentence, **kwargs):\n    """맨 앞 하이픈 뒤 공백 제거"""\n    if sentence is None: return ""\n    lines = sentence.splitlines()\n    out = []\n    for line in lines:\n        stripped = line.lstrip()\n        if stripped.startswith("- "):\n            stripped = "-" + stripped[2:]\n        out.append(stripped)\n    return "\\n".join(out)',

    "postprocess_remove_star_and_angle_for_lghv": 'def postprocess_remove_star_and_angle_for_lghv(text, **kwargs):\n    """LGHV: 별표와 꺾쇠 제거"""\n    if text is None: return ""\n    return re.sub(r"[\\*<>]", "", text)',

    "postprocess_remove_star_and_angle_for_skbb": 'def postprocess_remove_star_and_angle_for_skbb(text, **kwargs):\n    """SKBB: 큰따옴표, 음표, 소괄호, 꺾쇠 제거"""\n    if text is None: return ""\n    return re.sub(r\'["\\u266A\\u266B\\(\\)<>]\', "", text)',

    "postprocess_remove_wrong_punctuation": 'def postprocess_remove_wrong_punctuation(sentence: str, **kwargs) -> str:\n    """문장 앞의 . ... ? ! ~ 제거, 끝 쉼표 삭제, \'..\' 유지"""\n    if sentence is None:\n        return ""\n    lines = sentence.splitlines()\n    out = []\n    for line in lines:\n        line_text = line\n        kept = []\n        def _keep(m):\n            kept.append(m.group(0))\n            return f"\\uE000{len(kept) - 1}\\uE001"\n        line_text = re.sub(r"\\.\\.", _keep, line_text)\n        line_text = re.sub(r"^[\\.\\?\\!~]+\\s*", "", line_text)\n        line_text = re.sub(\n            r"\\uE000(\\d+)\\uE001",\n            lambda m: kept[int(m.group(1))],\n            line_text,\n        )\n        out.append(line_text)\n    if out:\n        out[-1] = re.sub(r",\\s*$", "", out[-1])\n    return "\\n".join(out)',

    "postprocess_reset_subtitles_from_list": 'def postprocess_reset_subtitles_from_list(subtitles, **kwargs):\n    """리스트 기반 인덱스 재부여 + 시간 순 정렬"""\n    if not subtitles:\n        return []\n    subtitles_sorted = sorted(subtitles, key=lambda s: s.start)\n    for i, sub in enumerate(subtitles_sorted, start=1):\n        sub.index = i\n    return subtitles_sorted',

    "postprocess_strip_whitespace": 'def postprocess_strip_whitespace(sentence: str, **kwargs) -> str:\n    """문장 앞뒤 공백 제거"""\n    return sentence.strip()',

    "postprocess_sync_overlap": 'def postprocess_sync_overlap(front_end_time, back_start_time, **kwargs):\n    """앞 종료==뒤 시작이면 앞 종료를 10ms 당김"""\n    from datetime import timedelta\n    if front_end_time == back_start_time:\n        adjusted = front_end_time - timedelta(milliseconds=10)\n        if adjusted < timedelta(0):\n            adjusted = timedelta(0)\n        return adjusted\n    return front_end_time',

    "postprocess_trim_speaker_spaces": 'def postprocess_trim_speaker_spaces(sentence: str, **kwargs) -> str:\n    """괄호 안쪽 공백 제거"""\n    sentence = re.sub(r"\\(\\s+", "(", sentence)\n    sentence = re.sub(r"\\s+\\)", ")", sentence)\n    sentence = re.sub(r"\\[\\s+", "[", sentence)\n    sentence = re.sub(r"\\s+\\]", "]", sentence)\n    return sentence',

    "validate_ellipsis_count": 'def validate_ellipsis_count(content, criterion=2, **kwargs):\n    """말줄임표의 마침표 개수 검증"""\n    content = content.replace("\\n", " ")\n    matches = re.findall(r"\\.{2,}", content)\n    for m in matches:\n        if len(m) == criterion:\n            return True\n    return False',

    "validate_hyphen_no_space_after_for_skbb": 'def validate_hyphen_no_space_after_for_skbb(content, **kwargs):\n    """하이픈 사용 규칙 검증: 줄 시작 \'-\' 다음에 공백이 오면 오류"""\n    if not content:\n        return False\n    for line in content.splitlines():\n        stripped = line.lstrip()\n        if not stripped.startswith("-"):\n            continue\n        if len(stripped) > 1 and stripped[1].isspace():\n            return True\n    return False',

    "validate_length": 'def validate_length(sentence, max_length=18, weight_kor=1.0, weight_etc=1.0, **kwargs):\n    """문장 길이 검증 (가중치 적용 가능)"""\n    if weight_kor == 1.0 and weight_etc == 1.0:\n        return len(sentence) > max_length\n    total_length = 0\n    for ch in sentence:\n        if "\\uAC00" <= ch <= "\\uD7A3":\n            total_length += weight_kor\n        else:\n            total_length += weight_etc\n    return total_length > max_length',

    "validate_length_lines": 'def validate_length_lines(content, max_length=18, valid_type="length", weight_kor=1.0, weight_etc=1.0, **kwargs):\n    """줄별 길이 검증"""\n    for sentence in content.split("\\n"):\n        if valid_type == "length":\n            if validate_length(sentence, max_length, weight_kor, weight_etc):\n                return True\n        elif valid_type == "byte":\n            if len(sentence.encode("utf-8")) > max_length * 2:\n                return True\n    return False',

    "validate_line_count": 'def validate_line_count(content, max_lines=2, **kwargs):\n    """자막 줄 수 검증"""\n    return max_lines <= content.count("\\n")',

    "validate_mosaic_count_for_skbb": 'def validate_mosaic_count_for_skbb(content, criterion=2, **kwargs):\n    """모자이크(*) 개수 검증"""\n    if not content:\n        return False\n    star_groups = re.findall(r"\\*+", content)\n    if not star_groups:\n        return False\n    for group in star_groups:\n        if len(group) != criterion:\n            return True\n    return False',

    "validate_overlapped_accumulated_lines": 'def validate_overlapped_accumulated_lines(subtitles, max_lines=3, **kwargs):\n    """연속 오버랩 그룹의 누적 줄 수 검사"""\n    if not subtitles:\n        return {}\n    ordered = sorted(subtitles, key=lambda x: (x.start, x.end, x.index))\n    errors = {}\n    def _lc(t):\n        if not t or not t.strip(): return 0\n        return t.count("\\n") + 1\n    def _flush(group):\n        if len(group) < 2: return\n        total = sum(_lc(s.content) for s in group)\n        if total <= max_lines: return\n        detail = f"연속 오버랩 총 {total}줄 ({max_lines}줄 초과)"\n        for s in group:\n            errors[s.index] = detail\n    current_group, current_end = [], None\n    for sub in ordered:\n        if not current_group:\n            current_group, current_end = [sub], sub.end\n            continue\n        if sub.start < current_end:\n            current_group.append(sub)\n            if sub.end > current_end: current_end = sub.end\n        else:\n            _flush(current_group)\n            current_group, current_end = [sub], sub.end\n    _flush(current_group)\n    return errors',

    "validate_overlapped_only_text_for_lghv": 'def validate_overlapped_only_text_for_lghv(front_content, back_content, front_end_time, back_start_time, **kwargs):\n    """LGHV: 오버랩된 싱크가 대사+대사인지 확인 (대괄호 태그 포함 시 오류)"""\n    if front_end_time <= back_start_time:\n        return False\n    def _single(t):\n        return t is not None and "\\n" not in t.strip()\n    def _bracket(t):\n        if t is None: return False\n        s = t.strip()\n        return s.startswith("[") and s.endswith("]") and len(s) > 2\n    if not (_single(front_content) and _single(back_content)):\n        return False\n    return _bracket(front_content) or _bracket(back_content)',

    "validate_overlapped_over_lines": 'def validate_overlapped_over_lines(front_content, back_content, front_end_time, back_start_time, max_lines=2):\n    """오버랩 + n줄 검증"""\n    if front_end_time <= back_start_time:\n        return False\n    def _lc(text):\n        if not text or not text.strip():\n            return 0\n        return text.count("\\n") + 1\n    return _lc(front_content) >= max_lines or _lc(back_content) >= max_lines',

    "validate_pair_characters": 'def validate_pair_characters(content, pair_char=None, **kwargs):\n    """괄호/따옴표/음표 짝 검증"""\n    if not content:\n        return False\n    if pair_char is None:\n        pair_char = {"(": ")", "[": "]", "<": ">", "\\u266A": "\\u266A"}\n    s = content.replace("\\n", " ")\n    for ch, close in pair_char.items():\n        if ch == close:\n            if s.count(ch) % 2 == 1:\n                return True\n    open_to_close = {o: c for o, c in pair_char.items() if o != c}\n    close_to_open = {c: o for o, c in open_to_close.items()}\n    stack = []\n    for ch in s:\n        if ch in open_to_close:\n            stack.append(ch)\n        elif ch in close_to_open:\n            if not stack:\n                return True\n            top = stack.pop()\n            if open_to_close[top] != ch:\n                return True\n    return len(stack) != 0',

    "validate_special_characters": 'def validate_special_characters(content, **kwargs):\n    """사용할 수 없는 특수 기호 검증 (음표 미허용)"""\n    import string\n    content = content.replace("\\n", " ")\n    ansi_chars = (\n        "".join(chr(i) for i in range(0xAC00, 0xD7A4))\n        + string.ascii_letters + string.digits + string.punctuation + " "\n    )\n    for char in content:\n        if char not in ansi_chars:\n            return True\n    return False',

    "validate_special_characters_allow_music_note": 'def validate_special_characters_allow_music_note(content, **kwargs):\n    """사용 불가 특수 문자 검증 (\\u266B는 허용)"""\n    import string\n    content = content.replace("\\n", " ").replace("\\u2018", "\'").replace("\\u2019", "\'")\n    punctuation_without_slash = string.punctuation.replace("/", "")\n    ansi_chars = (\n        "".join(chr(i) for i in range(0xAC00, 0xD7A4))\n        + string.ascii_letters + string.digits + punctuation_without_slash + " "\n    )\n    for char in content:\n        if char == "\\u266A":\n            continue\n        if char not in ansi_chars:\n            return True\n        if char == "/":\n            return True\n    return False',

    "validate_sync_negative_or_zero": 'def validate_sync_negative_or_zero(start_time, end_time, **kwargs):\n    """싱크 시간이 마이너스 혹은 0인지 확인"""\n    return True if start_time >= end_time else False',

    "validate_sync_overlapped": 'def validate_sync_overlapped(front_content, back_content, front_end_time, back_start_time, **kwargs):\n    """오버랩(싱크 겹침) 검증"""\n    if front_end_time is None or back_start_time is None:\n        return False\n    return front_end_time > back_start_time',

    "validate_sync_short_duration": 'def validate_sync_short_duration(start_time, end_time, min_duration_sec=1.0, **kwargs):\n    """자막 길이가 min_duration_sec 미만인지 검증"""\n    if start_time is None or end_time is None:\n        return False\n    duration = (end_time - start_time).total_seconds()\n    return 0 < duration < min_duration_sec',

}